// @flow
import {StyleSheet} from 'react-native';
import {Colors, Metrics, AppStyles, Fonts} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
  },

  logo: {width: 96, height: 112},
  lineThrough: {
    height: 0.5,
    backgroundColor: Colors.grey4,
    position: 'absolute',
    top: 6,
    left: 0,
    right: 0,
  },
  ORTextWrapper: {
    backgroundColor: Colors.white,
    width: 110,
    alignSelf: 'center',
  },
  socialIcon: {
    width: 50,
    height: 50,
    ...AppStyles.mLeft10,
    ...AppStyles.mRight10,
  },
  logo: {
    marginTop: Metrics.doubleBaseMargin,
    alignSelf: 'center',
    height: 100,
    width: Metrics.screenWidth - 150,
    resizeMode: 'contain',
  },
  button: {
    marginTop: Metrics.doubleBaseMargin,
    backgroundColor: Colors.blue,
    borderRadius: 25,
    alignItem: 'center',
    justifyContent: 'center',
    paddingVertical: Metrics.smallMargin + 5,
    width: Metrics.screenWidth * 0.5,
    marginVertical: Metrics.smallMargin,
    alignSelf: 'center',
  },
  VehicleInput: {
    width: Metrics.screenWidth - 40,
    //flex: 1,
    backgroundColor: Colors.white,
    borderRadius: Metrics.textInputBorder,
    padding: 15,
    marginTop: 3,
    fontFamily: Fonts.type.medium,
    // color: Colors.grey5,
    fontSize: Fonts.size.normal,
    marginVertical: 10,
  },
  uploadView: {
    backgroundColor: Colors.blue,
    alignSelf: 'center',
    marginLeft: 70,
    marginTop: -25,
    borderRadius: 20,
    height: 20,
    width: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadIcon: {backgroundColor: 'white', height: 10, width: 10},
  modalStyle: {
    width: Metrics.screenWidth * 0.85,
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 5,
    justifyContent: 'center',
    borderRadius: 20,
    paddingVertical: 10,
  },
  crossBtn2: {
    // width: 2.2 * vh,
    // height: 2.2 * vh,

    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -1,
    top: 0,
  },
  closeIcon: {
    width: 10,
    height: 10,
    resizeMode: 'contain',
  },
  docView: {
    flexDirection: 'row',
    // backgroundColor: 'gray',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
    borderColor: Colors.blue,
    borderWidth: 0.5,
  },
  imageDoc: {
    height: 40,
    width: 70,
    resizeMode: 'cover',
    borderRadius: 5,
  },
  input: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    //   flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingHorizontal: 15,
    height: 40,
    width: Metrics.screenWidth - 80,
    // color: Colors.grey5,
    marginTop: 10,
    borderColor: 'gray',
    borderWidth: 0.5,
    alignSelf: 'center',
    borderRadius: Metrics.textInputBorder,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,

    elevation: 9,
  },
  dropdownView: {
    backgroundColor: 'white',
    borderRadius: 20,
    marginBottom: 10,
    position: 'absolute',
    zIndex: 999,
    width: Metrics.screenWidth * 0.5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    bottom: 0,
    left: 50,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  uploadImage: {
    width: Metrics.screenWidth * 0.18,
    height: Metrics.screenHeight * 0.09,
    position: 'relative',
  },
  countPlacement: {
    position: 'absolute',
    top: 0,
    right: 20,
    backgroundColor: 'white',
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  uploadImagePlacement: {
    position: 'absolute',
    bottom: 25,
    right: 10,
  },
});
