// @flow
import {StyleSheet} from 'react-native';
import {Colors, Metrics, AppStyles, Fonts} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  logo: {
    marginTop: Metrics.doubleBaseMargin,
    alignSelf: 'center',
    height: 100,
    width: Metrics.screenWidth - 150,
    resizeMode: 'contain',
  },
  uploadView: {
    alignSelf: 'center',
    marginLeft: 70,
    marginTop: -30,
  },
  uploadIcon: {height: 30, width: 30},
  button: {
    backgroundColor: Colors.blue,
    borderRadius: 25,
    alignItem: 'center',
    justifyContent: 'center',
    paddingVertical: Metrics.smallMargin,
    marginHorizontal: Metrics.doubleBaseMargin + Metrics.doubleBaseMargin,
    marginVertical: Metrics.baseMargin,
  },
  input: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Metrics.textInputBorder,
    padding: 12,
    marginTop: 3,
    fontFamily: Fonts.type.medium,
    // color: Colors.grey5,
    fontSize: Fonts.size.normal,
    marginVertical: 10,
  },
  Icon: {height: 20, width: 20},
  modalStyle: {
    flex: 1,
    //  width: Metrics.screenWidth * 0.9,
    alignSelf: 'center',
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderRadius: 20,
    // height: Metrics.screenHeight * 0.5,
    marginHorizontal: Metrics.baseMargin,
  },
  closeIcon: {
    width: 10,
    height: 10,
    resizeMode: 'contain',
  },
  docsView: {
    width: Metrics.screenWidth * 0.72,
    minHeight: Metrics.screenHeight * 0.6,
    backgroundColor: 'white',
    borderRadius: 5,
    flexDirection: 'row',
    marginBottom: 10,
    paddingHorizontal: 4,
    paddingVertical: 1,
    justifyContent: 'space-between',
  },
  imageDoc: {
    height: 40,
    width: 70,
    resizeMode: 'cover',
    borderRadius: 5,
  },
  docView: {
    flexDirection: 'row',
    // backgroundColor: 'gray',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
    borderColor: Colors.blue,
    borderWidth: 0.5,
    //  marginBottom: 0.7,
  },
  crossBtn2: {
    // width: 2.2 * vh,
    // height: 2.2 * vh,

    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -1,
    top: 0,
  },
  swipperContainer: {
    overflow: 'hidden',
    paddingVertical: Metrics.screenHeight * 0.02,
    height: Metrics.screenHeight * 0.72,
  },
  dotContainer: {
    height: Metrics.screenHeight * 0.6,
  },
});
